### ISSUE TITLE
src is undefined

### ISSUE THREAD

**Issue by missma19** [nwjs/grunt-nw-builder#211]
### Issue Type

- [x] Bug Fix

### Current/Missing Behaviour

I'm getting the error: "Fatal error: Expected src to be a string or an array of strings. Got undefined instead.", when running nwjs:src.

### Expected/Proposed Behaviour

src is set to the string, which is set in the code.

```
nwjs: {
	options: {
			xxx
	},
	src: "./build/src_<%= packageconfig.language %>/**/*",
	},
```

### Additional Info

I get the same error from version 4.6.1 to 4.7.7.
Version 4.6.0 gives a totally different error. 

The grunt-file works in version 3.7.1 without problems.

- Operating System: docker build linux/amd64
- Node version: 22
- NW.js version: 0.88.0

**Comment by missma19** [comment]
Hi, 
I upgraded from 3.6.0. 
Glob is not enabled. (There is a mistake in the readme. It says twice "when glob is enabled")

I don't know exactly what you mean with stack trace, but i guess this is what you want.

```
#17 2.416 Running "nwjs:src" (nwjs) task
#17 2.417 Fatal error: Expected src to be a string or an array of strings. Got undefined instead.
#17 2.418 Error: Expected src to be a string or an array of strings. Got undefined instead.
#17 2.418     at Object.<anonymous> (/master/packaging/node_modules/grunt-nw-builder/tasks/nw.js:15:15)
#17 2.418     at Object.<anonymous> (/master/packaging/node_modules/grunt/lib/grunt/task.js:252:15)
#17 2.418     at thisTask.fn (/master/packaging/node_modules/grunt/lib/grunt/task.js:70:16)
#17 2.418     at Object.<anonymous> (/master/packaging/node_modules/grunt/lib/util/task.js:294:30)
#17 2.418     at Task.runTaskFn (/master/packaging/node_modules/grunt/lib/util/task.js:244:24)
#17 2.418     at Task.<anonymous> (/master/packaging/node_modules/grunt/lib/util/task.js:293:12)
#17 2.418     at /master/packaging/node_modules/grunt/lib/util/task.js:220:11
#17 2.418     at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
#17 ERROR: process "/bin/sh -c grunt package:releases --lang=de --os=osx64" did not complete successfully: exit code: 3
------
```
